### PR TITLE
Support requesting forecasts for this/next weekend

### LINKED ISSUE #21: Asking for the weather this/next weekend
I'd like to ask questions like "What will the weather be this weekend?" and hear the forecasts for Saturday and Sunday spoken.

It looks like I can request each day individually. But when I'm making weekend plans, it makes more sense conversationally to request the weather in a batch, and to get back both forcasts at once, than it does to ask for each day individually.

Thanks!

### PR DESCRIPTION
**Pull request by ndarilek**
Closes #21

### CODE REVIEW

**Comment by penrods** [comment]
Hello, @ndarilek, thank you for helping with the Mycroft project!  I appreciate this additoin, it definitely fixes an overlooked common usage.
  
To protect yourself, the project, and users of Mycroft technologies we require a Contributor Licensing Agreement (CLA) before accepting any code contribution.   This agreement makes it crystal clear that along with your code you are offering a license to use it within the confines of this project. You retain ownership of the code, this is just a license.
  
  Please visit https://mycroft.ai/cla to initiate this one-time signing. Thank you!

**Comment by penrods** [comment]
Hey @ndarilek, pinging you on the CLA so we can get this merged!

**Comment by ndarilek** [comment]
Sorry, just filled out the CLA request and am waiting for the email. Not 
sure if it's supposed to happen near instantaneously or if the process 
is manual. Haven't gotten anything in the past 5 minutes or so.

**Comment by penrods** [comment]
It is still manual, so can take a bit.  :)

You should have an email now.

**Comment by ndarilek** [comment]
I'd like to sign your CLA, but I'm blind, and the hellosign interface is 
inaccessible to the point of being unusable. Sorry, not sure what to do 
from here.

**Comment by penrods** [comment]
Hmm, that is good to know.  Well, I am happy to work outside that mechanism with you.  I can send the CLA as a PDF if you can read through that easier.  We can then do something special so you can "digitally sign" it, or you could literally sign and send back an image of it.

What would work best?  This is an important step, but I don't want this to become an ordeal for you!

**Comment by ndarilek** [comment]
Thanks! Can I PGP-sign a PDF of the CLA? My key is on Keybase, with 
proofs that I own this GitHub account.

**Comment by penrods** [comment]
I can work with that!  I will email you the PDF using the address you used to request the CLA originally.

**Pull request closed without merging**
