### PR TITLE
fix for nl-nl locale dialogs

### PR DESCRIPTION
**Pull request by Aduen**
#### Description
Fixes nl-nl locale `current-humidity-location.dialog` `current-weather-local.dialog` `current-weather-location.dialog`. Previous version crashed on KeyErrors. This was due to the `current-weather-*` dialogs contained min/max temperature template keys that not were not supplied. The `current-temperature-high-low.dialog` is added to address the high-low dialog.

Dutch translations for the vocabulary are also added, based on the German and English versions.

#### Type of PR
If your PR fits more than one category, there is a high chance you should submit more than one PR. Please consider this carefully before opening the PR.

- [X] Bugfix
- [ ] Feature implementation
- [ ] Refactor of code (without functional changes)
- [ ] Documentation improvements
- [ ] Test improvements

#### Testing
Test for location: "Wat is het weer in Amsterdam?" (How is the weather in Amsterdam?) produced adequate results.
Test for local: "Hoe is het weer?" (How is the weather?) produced adequate results.

#### Documentation
Documentation was copied from the english versions and kept in the files

### CODE REVIEW

**Comment by krisgesling** [comment]
Hey there, thanks for this - it looks right from a surface look.

The only thing that seems out of place is that there is an `__init__` file added that appears to be a duplicate without the file extension. Am I right in assuming that this can be dropped from the pull request? Or were you proposing changes in the  Skill itself as well?

**Comment by Aduen** [comment]
I gues my IDE snuck that one in... I'll have a talk with him. You can drop the `__init__`

**Comment by Aduen** [comment]
Sorry, I am not having my day

**Comment by krisgesling** [comment]
Haha, no worries - happens to the best of us. I've removed that erroneous file and merging now.

**Pull request merged**
