### PR TITLE
Changes for Basque language

### PR DESCRIPTION
**Pull request by e-gor**
Changes for Basque language
===========================

#### Description

These changes, along with those sent to other repos, make Mycroft work in Basque language.

Made by Elhuyar, Talaios and Skura

#### Type of PR

Feature implementation

### CODE REVIEW

**Comment by chrisveilleux** [comment]
This PR will need to change to use the new vocabulary and dialog file naming conventions implemented in the major refactor.

**Comment by krisgesling** [comment]
Hey Igor, this is some bad timing on this one, and it's also the Skill that has by far the most vocab and dialog files :(

We need to setup a mechanism to import new language contributions like this into our translate.mycroft.ai platform. Though we have bigger plans to review how these translations are handled by shifting them into central language packs instead of needing to create pull requests against every single Skill. It's hard enough doing them for Skills under the Mycroft organization, even worse that every Skill author also needs to review translation changes and resubmit their Skill back to the Marketplace.

So unfortunately I don't have an easy solution for you atm, but definitely see the pain.

**Comment by e-gor** [comment]
All right, but due to holidays, I do not think I will be able before September...

**Comment by e-gor** [comment]
Refactoring of dialog and vocab files for Basque language done.

**Comment by krisgesling** [comment]
Looks all good to me.

The `location.voc` shouldn't really need all the locations defined. From memory it's used as a backup for locations that aren't properly detected by the regex, but it won't hurt.

**Pull request merged**
