### PR TITLE
Rename filename for local weather

### PR DESCRIPTION
**Pull request by kfezer**
As per:
https://github.com/MycroftAI/mycroft-skills/pull/80

### CODE REVIEW

**Comment by kfezer** [comment]
also, this was by @chrison999 originally.

**Comment by forslund** [comment]
Tried this PR and it works fine. Would be good to have it merged

**Comment by kfezer** [comment]
Yeah, I don't have write access to these.

**Comment by forslund** [comment]
I'll bug @augustnmonteiro about it then =)

**Comment by kfezer** [comment]
I am. I'm making him feel really guilty about it...

**Pull request merged**
